
["银影AI 设置"]
	#API URL
	apiUrl = "https://api-yinying-ng.wingmark.cn/v1"
	#API 接口
	apiInterface = "/chatWithCyberFurry"
	#Token
	token = "yinying-2L8NvWk82J6urz85dree23e6aesOCfOnQUo6M7ojggty"
	#AppID
	appid = "lanhuobot"
	#Model
	model = "yinyingllm-latest"
	#System Prompt
	systemPrompt = "你的名字叫银影，是翎迹网络开发的仿生灰狼"
	#显示名称
	showName = "银影"
	#保存聊天
	saveChat = true
	#次数 / min
	times = 188

	["银影AI 设置".Variables]
		#昵称
		nickname = "没有哦"
		#设定
		furryCharacter = "没有哦"
		#微调提示词
		promptPatch = "你在和一群人对话,每个人以 [id] 前缀区分,前缀只是用户的唯一标识符,你可以理解为用户id,你可以根据这个id来判断用户是否相同.前缀和用户的设定或者其他任何信息没有任何关系."

